### Numpy 学习
Numpy是Python的一个很重要的第三方库，很多其他科学计算的第三方库都是以Numpy为基础建立的。

In [9]:
from numpy import *
a = [1,.2,3,4]
# a+1
a = array(a)
a
a+1

# 与另一个 array 相加，得到对应元素相加的结果：
b = array([1,3,4,6])
a+b

# 对应元素相乘：

a*b

# 乘方

a ** b


array([1.000e+00, 8.000e-03, 8.100e+01, 4.096e+03])

In [23]:
# 提取数组中的元素
a[0]
a[:2]
a[-2]
a[-2:]
a[:2] + a[-2:]

# 查看 array 的形状：

a.shape
a.shape = 2,2
a


array([[1. , 0.2],
       [3. , 4. ]])

In [47]:
# 多维数组相加
c = [1,2,3,4,5,6]
c = array(c)
c + c
c.shape
c.shape = 3,2
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [55]:
# 画图
a = linspace(0, 2*pi, 21)
a
b = sin(a)
b
b >= 0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False, False, False, False, False, False,
       False, False, False])

In [73]:
# 产生一个复数数组
a = array([1 + 1j, 2, 3, 4])
a
a.dtype
a.real
a.imag
a.imag = [1,2,3,4]
a
a.conj()

# 指定数组类型
a = array([0,1.0,2,3])
a
a.dtype
a.nbytes

a = array([0,1.0,2,3],dtype=float32)
a.dtype
a.nbytes

# 写入二进制数据
a = array([102,111,212], 
          dtype=uint8)
a.tofile('foo.dat')
import os
os.remove('foo.dat')

In [81]:
# 类型转换

a = array([1.5, -3], dtype=float32)
a
# asarray 函数
b = asarray(a, dtype=float32)
b
b is a

True

In [89]:
# 数组方法
# %pylab
a = array([[1,2,3], [4,5,6]])
sum(a)
# 指定求和的维度：
# 沿着第一维求和：
sum(a, axis=0)

# 沿着第二维求和：
sum(a, axis=1)

# 沿着最后一维求和：
sum(a, axis=-1)
a.sum()

# 求积

a.prod()

720

In [141]:
# 求最大最小值
from numpy.random import rand
a = rand(3,4)
%precision 3
# a.min()
# a.min(axis=0)
# a.max()
# a.max(axis=-1)

# 最大值 和最小值
a.argmin()

# 均值
a = array([[1,4,3],[2,5,6]])
a.max()
a.min(axis=0)
a.max()
a.max(axis=0)
a.mean(axis=-1)

# 标准差
# 用 std 方法计算标准差：
a.std(axis=1)

# 用 var 方法计算方差：
a.var(axis=1)

# clip 方法
a
a.clip(3,5)

# ptp 方法
# 计算最大值和最小值之差：
a.ptp()
a.ptp(axis=0)

# round 方法

a = array([1.35, 2.5, 1.5])
a.round()
a.round(decimals=1)


array([1.4, 2.5, 1.5])

In [153]:
# 数组排序
# sort 函数
names = array(['bob', 'sue', 'jan', 'ad'])
weights = array([20.8, 93.2, 53.4, 61.8])
# sort 返回的结果是从小到大排列的。
sort(names)
sort(weights)

# argsort 函数  返回从小到大的排列在数组中的索引位置：
ordered_indices = argsort(weights)
ordered_indices
# 可以用它来进行索引：
weights[ordered_indices]
names[ordered_indices]
names

# sort 和 argsort 方法
data = array([20.8,  93.2,  53.4,  61.8])
data.argsort()
# argsort 方法与 argsort 函数的使用没什么区别，也不会改变数组的值。
data.sort()
data


array([20.8, 53.4, 61.8, 93.2])

In [171]:
# 二维数组排序
a = array([
        [.2, .1, .5], 
        [.4, .8, .3],
        [.9, .6, .7]
    ])
# sort(a)
sort(a, axis = -1)

from numpy.random import rand
data = rand(100)
data.sort()
data

bounds = .4, .6
bounds
low_idx, high_idx = searchsorted(data, bounds)
data[low_idx:high_idx]

array([0.414, 0.418, 0.424, 0.425, 0.438, 0.465, 0.466, 0.471, 0.488,
       0.488, 0.499, 0.503, 0.509, 0.517, 0.525, 0.53 , 0.53 , 0.556,
       0.562, 0.564, 0.579, 0.591])

In [219]:
# 数组形状
a = arange(6)
a
# 修改数组的形状
a.shape = 2,3
a
# 与之对应的方法是 reshape ，但它不会修改原来数组的值，而是返回一个新的数组：
# shape 和 reshape 方法不能改变数组中元素的总数，否则会报错：
a.reshape(3,2)

# 使用 newaxis 增加数组维数
a =arange(3)
shape(a)
y =a[newaxis,:]
shape(y)
# 根据插入位置的不同，可以返回不同形状的数组：
y = a[:,newaxis]
shape(y)
# 插入多个新维度：
y = a[newaxis, newaxis, :]
shape(y)

# squeeze 方法去除多余的轴

a = arange(6)
a.shape
a.shape=(2,1,3)
a
# squeeze 返回一个将所有长度为1的维度去除的新数组。
b = a.squeeze()
b.shape

# 数组转置
a
a.transpose()
a.T

a = arange(60)
a.shape = 3,4,5
b = a.T
b.shape
a = arange(6)
a.shape
a.shape = (2,3)
b = a.T
b.shape
b[1]=12
b


array([[ 0,  3],
       [12, 12],
       [ 2,  5]])

In [241]:
# 数组连接
x = array([
        [0,1,2],
        [10,11,12]
    ])
y = array([
        [50,51,52],
        [60,61,62]
    ])
print(x.shape)
print(y.shape)
z = concatenate((x,y))
z
z.shape
z = concatenate((x,y), axis=-1)
print(z)
z.shape
z = array((x,y))
z
print("\n===============================\n")
print(vstack((x, y)))
print()
print(hstack((x, y)))
print()
print(dstack((x, y)))

(2, 3)
(2, 3)
[[ 0  1  2 50 51 52]
 [10 11 12 60 61 62]]


[[ 0  1  2]
 [10 11 12]
 [50 51 52]
 [60 61 62]]

[[ 0  1  2 50 51 52]
 [10 11 12 60 61 62]]

[[[ 0 50]
  [ 1 51]
  [ 2 52]]

 [[10 60]
  [11 61]
  [12 62]]]


In [252]:

# flatten 方法的作用是将多维数组转化为1维数组：
a = array([[0,1],[2,3]])
b = a.flatten()
b[0]=10
print(a)
print(b)
# flat 属性
b = a.flat
b[3]
# 此时修改 b 的值会影响 a
print('\n=================\n')
print(a)
b[0]=12
print(a)

[[0 1]
 [2 3]]
[10  1  2  3]


[[0 1]
 [2 3]]
[[12  1]
 [ 2  3]]
